---
# roles/rhel_patch/tasks/main.yml

- name: Configure Subscription Manager
  ansible.builtin.include_tasks: subscription_manager.yml
  when: patch_subscription_manager | bool
  tags: [subscription]

- name: Run DNF update
  ansible.builtin.include_tasks: dnf_update.yml
  tags: [dnf]

- name: Handle reboot
  ansible.builtin.include_tasks: reboot.yml
  tags: [reboot]
